#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 28 11:08:33 2018

@author: ekerns
"""

#Load packages
import pandas
import scipy
import scipy.integrate as spint
from plotnine import *

#Custom function 
def Ros_Mac_Sim(b,a,w,d,e,s)

    dHdt = b * H * (1 - a * H)- w * (H/(d+H)) * P

    dPdt = e * w * (H / (d+H)) * P - s * P
    
#Define parameters(do not change)
params = (0.8,0.001,5,400,0.07,0.2) #(b,a,w,d,e,s)

#Set initial values for state variables(change)
H0 = y0
P0 = y1

#set time steps
times = range(0,100)

#simulate model using odeint
y0 = [500,120] #y0 passed as H and y1 passed as p 
modelRos_Mac_Sim = spint.odeint



#Mac's Code
import pandas as pd
import scipy
import scipy.integrate as spint
from plotnine import *

def Lot_Vol_Sim(y,t0,b,a,e,s):
    
    H = y[0]
    P = y[1]
    
    dH_dt = b * H - a * P * H
    dP_dt = e * a * P * H - s * P
    
    return [dH_dt,dP_dt]

#Trial One - Given Parameters
#b = 0.5; a = 0.02; e = 0.1; s = 0.2; H0 = 25; P0 = 5
times = range(0,100) #Passed as t0
y0=[25,5] #Passed as H and P, respectively
params = (0.5,0.02,0.1,0.2) #Passed as (b,a,e,s)

#Running the simulation using scipy integrate
sim = spint.odeint(func=Lot_Vol_Sim,y0=y0,t=times,args=params)
#Creating a dataframe
simdf=pd.DataFrame({"t":times,"H":sim[:,0],"P":sim[:,1]})
a=ggplot(simdf,aes(x="t",y="H"))+geom_point()+geom_line()+ylab("Population")+geom_line(simdf,aes(x="t",y="P"),color="red")+theme_classic()
print(a)